languageCode = "en-us"
title = "Wassel Alazhar"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  twitter = "https://twitter.com/wasselovski"
  github = "https://github.com/jcraftsman"
  linkedin = "https://www.linkedin.com/in/wassel-alazhar-8b991011/"
  meetup = "https://www.meetup.com/fr-FR/crafting-datascience"
  gitlab = ""
  facebook = ""
  instagram = ""
  youtube = ""
  mastodon = ""
  featured_image = "images/featured.jpg"
  recent_posts_number = 3
  media_folder= "static/images/" 
  public_folder= "/images/" 
